# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.4.0 
      
    - name: Setup Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Merge Conflict finder
      uses: olivernybroe/action-conflict-finder@v4.0

    - name: Install dependents (with cache)
      run: pnpm install

    - name: Run ESLint on expo
      run: npm run lint:expo

    - name: Run ESLint on db
      run: npm run lint:db
      
    - name: Generate Schema
      run: npm run generate

    - name: Build app
      run: npm run build --if-present

